### ISSUE TITLE
Remove branding from DNS Manager

### ISSUE THREAD

**Issue by tsiedsma** [apisnetworks/apnscp#32]
DNS Manager has the following text:

Set MX to Apis/Gmail provisions DNS to let Apis or Gmail handle e-mail on the domain. Execute this command to setup hosted Gmail.
Clone External NS MX Records copy public MX records, which is useful to avoid downtime while moving e-mail to Apis.

**Comment by msaladna** [comment]
Resolved in v3.1.41

**Comment by tsiedsma** [comment]
![lh-C2Wpq](https://user-images.githubusercontent.com/2625597/81131371-988f5380-8f10-11ea-830b-3b8b5246a6f5.png)
I'm still seeing it after an upgrade.

**Comment by msaladna** [comment]
Flush Redis cache, `echo FLUSHDB | redis-cli -s /usr/local/apnscp/storage/run/redis.sock`.

application.{spec,yml} is cached for [1 day](https://gitlab.com/apisnetworks/apnscp/-/blob/master/lib/html/page_container.php#L438).
